gbere_simple_auth:
    sender:
        email: sender@email.com
        name: Sender Name
    user:
        entity: Gbere\SimpleAuth\Entity\User
        encoder_algorithm: auto
    confirm_registration_by_email: true
    # remember_me_lifetime: ~       # Disabled
    remember_me_lifetime: 604800    # 604800 = 7 days in seconds
