security:
    encoders:
        Gbere\Security\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        gbere_security_main_provider:
            entity:
                class: Gbere\Security\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        gbere_security_main_firewall:
            anonymous: lazy
            provider: gbere_security_main_provider
            guard:
                authenticators:
                    - Gbere\Security\Security\LoginFormAuthenticator
            logout:
                path: gbere_security_logout
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 2592000 # 30 days in seconds
                
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # Tests
        - { path: ^/gbere-security-test-role-admin, roles: ROLE_ADMIN }
        - { path: ^/gbere-security-test-role-user, roles: ROLE_USER }
        # End tests
        - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED }
