language: php
sudo: false

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - ACTION="update"
    - DATABASE_URL=mysql://travis:@127.0.0.1:3306/test?serverVersion=5.7
    - SYMFONY_VERSION="last"

matrix:
  fast_finish: true
  include:
    - os: linux
      php: 7.2
    - os: linux
      php: 7.3
      env: ACTION="install"
    - os: linux
      php: 7.4
    - os: linux
      php: nightly
    - os: linux
      php: 7.2
      env: SYMFONY_VERSION="4.4"
    - os: linux
      php: 7.3
      env: SYMFONY_VERSION="4.4"
    - os: linux
      php: 7.4
      env: SYMFONY_VERSION="4.4"
    - os: linux
      php: nightly
      env: SYMFONY_VERSION="4.4"
  allow_failures:
    - php: nightly

before_install:
  - composer self-update
  - '[[ "$ACTION" == "install" ]] || echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini'
  - '[[ "$SYMFONY_VERSION" == "last" ]] || cp "./.travis/symfony${SYMFONY_VERSION}/composer.json" ./composer.json'
  - '[[ "$SYMFONY_VERSION" == "last" ]] || cp "./.travis/symfony${SYMFONY_VERSION}/phpstan.neon" ./phpstan.neon'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install:
  - composer $ACTION
  - ./vendor/bin/simple-phpunit install

script:
  - ./bin/console doctrine:schema:update --force
  - ./bin/console doctrine:fixtures:load --no-interaction
  - SYMFONY_DEPRECATIONS_HELPER=weak ./vendor/bin/simple-phpunit
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || ./vendor/bin/php-cs-fixer fix --diff --dry-run -v'
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || ./vendor/bin/phpstan analyse -c phpstan.neon --no-progress -vvv --memory-limit=1024M'
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || ./vendor/bin/phpstan analyse -c phpstan-tests.neon --no-progress -vvv --memory-limit=1024M'
  - composer validate
  - ./bin/console lint:container

notifications:
  email: false
