translation:
    locales: ["en"]
    edit_in_place:
        enabled: false
        config_name: simple_auth
    configs:
        simple_auth:
            dirs: ["%kernel.project_dir%/src/Resources/views", "%kernel.project_dir%/src"]
            output_dir: "%kernel.project_dir%/src/Resources/translations"
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
    symfony_profiler:
        enabled: true
    webui:
        enabled: true
