services:
    _defaults:
        autowire: true
        autoconfigure: true

    Gbere\SimpleAuth\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Gbere\SimpleAuth\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']


    Gbere\SimpleAuth\Service\Mailer:
        arguments:
                ['@mailer.mailer', '@parameter_bag']
    gbere_simple_auth.mailer:
        alias: Gbere\SimpleAuth\Service\Mailer

    Gbere\SimpleAuth\Entity\User:
    Gbere\SimpleAuth\Repository\UserRepository:
        arguments:
                ['@Doctrine\Common\Persistence\ManagerRegistry']

    Gbere\SimpleAuth\Entity\AdminUser:
    Gbere\SimpleAuth\Repository\AdminUserRepository:
        arguments:
                ['@Doctrine\Common\Persistence\ManagerRegistry']
