gb_security_test_user:
    path:         /gbere-security-test-user
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: tests/hi.html.twig
gb_security_test_admin:
    path:         /gbere-security-test-admin
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: tests/hi.html.twig
